compatibility_flags = [ "nodejs_compat_v2" ]
pages_build_output_dir = './dist'
name = 'clerk-astro-cloudflare-quickstart'
compatibility_date = '2024-09-02'

[vars]
PUBLIC_CLERK_PUBLISHABLE_KEY = "pk_test_<your_publishable_key_here>"
PUBLIC_CLERK_SIGN_IN_FORCE_REDIRECT_URL= "/protected"
PUBLIC_CLERK_SIGN_IN_URL="/sign-in"
PUBLIC_CLERK_SIGN_UP_URL="/sign-up"
